import { routing } from "@/locales/routing"
import ThemeProvider from "@/theme"
import type { Metadata } from "next"
import { hasLocale, NextIntlClientProvider } from "next-intl"
import { notFound } from "next/navigation"
import GuestLayout from "@/layout/guest"
import { NextAuthProvider } from "@/auth/context/next-auth"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ locale: string }>
}>) {
  const { locale } = await params
  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }
  return (
    <html lang={locale}>
      <body style={{ margin: 0 }}>
        <NextAuthProvider>
          <NextIntlClientProvider>
            <ThemeProvider>
              <GuestLayout>{children}</GuestLayout>
            </ThemeProvider>
          </NextIntlClientProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
